# Generated by Django 2.0 on 2018-01-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('totalvalue', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('ethereum_address', models.CharField(max_length=100, null=True)),
                ('ripple_address', models.CharField(max_length=100, null=True)),
                ('api_key', models.CharField(max_length=100, null=True)),
                ('api_secret', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('exchange_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cryptos', to='wallet.Exchange')),
            ],
        ),
        migrations.AddField(
            model_name='crypto',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cryptos', to='wallet.Wallet'),
        ),
    ]
